### ISSUE TITLE
[1.15.2] Incompatiblity with Performant, Crashing when item becomes item entity.

### ISSUE THREAD

**Issue by Zidiath** [thedarkcolour/Future-MC#125]
Forge: 31.1.47
FutureMC: 1.15.2-1.0.0
Kotlinforforge: 1.15-2.07m
MixinBootstrap: 1.0.2
Performant:1.15-2.07m

After narrowing the mods down I have found that when using Future-MC with performant it causes the items in Future-MC to crash the game when dropped to the ground. Any method of causing the item to appear in the world causes the crash ex: dropping, /give, broken chest, etc.

[Future-MC Crash](https://pastebin.com/zF4g4Ywk)

[Future-MC Log](https://pastebin.com/vJn338TP)

**Comment by thedarkcolour** [comment]
This is an issue on Performant's side. It makes incompatible changes to Minecraft's bytecode that my mod uses to avoid coremods. Since they don't want to post up-to-date sources, I will put this on hold and make an issue on their repo until they fix it on their side or I am able to find my own solution. I should let you know that Performant exaggerates its performance improvements, which are microoptimizations in the AI of rare animals.

**Comment by thedarkcolour** [comment]
This isn't controllable by me. I can't see the author's code, so I have no idea what's changing. Seems that they edit the ItemEntity class.

**Comment by thedarkcolour** [comment]
Fixed in Performant 2.08m
