### ISSUE TITLE
[1.12.2] Composter flowers bug

### ISSUE THREAD

**Issue by throaway123869** [thedarkcolour/Future-MC#269]
Blue orchids, Alliums, and any flower with an ID of red_flower and a metadata value above 0, cannot be composted.  Should be a simple fix.

**Comment by democat3457** [comment]
This could be due to that ItemStacks with metas are stored in the getSubItems() method, but it's never being checked, so only the default item is being added regardless of meta value

I'm not sure if crafttweaker automatically expands the bracket handler into individual ItemStacks or keeps it as requiring a getSubItems call
