### ISSUE TITLE
[1.12.2] Crash on launch with intellij 

### ISSUE THREAD

**Issue by Florent-Marc** [thedarkcolour/Future-MC#306]
In load of mod. the game crash :
[crash-2022-08-01_18.08.21-client.txt](https://github.com/thedarkcolour/Future-MC/files/9235462/crash-2022-08-01_18.08.21-client.txt)

**Comment by thedarkcolour** [comment]
Use older version of forge

**Comment by thedarkcolour** [comment]
Or include Future MC's access transformers with your mod cause Forge 2848+ changed how access transformers are declared

**Comment by Florent-Marc** [comment]
For the change of version it will not be possible. But I would be interested to know how to include transformers. And thank you for answering me.

**Comment by thedarkcolour** [comment]
You [can copy + paste these](https://github.com/thedarkcolour/Future-MC/blob/9d2b821b05909a95340f36dff248b15accdb8c16/src/main/resources/META-INF/futuremc_at.cfg) into an access transformer for your own mod, refresh Gradle, and then you can remove them before compiling a jar of your mod.

**Comment by thedarkcolour** [comment]
I believe this is a ForgeGradle issue, since FutureMC should load just fine outside of dev. The only feature of the Forge versions past 2847 is support for ForgeGradle 3+, which changes how access transformers are detected. FG3 is meant for newer versions of Minecraft and it does not detect old <1.12 access transformers, so the solution is to copy + paste them when you're using them or to not bother using the new Forge at all.

**Comment by Florent-Marc** [comment]
Ok thank you very much for this information
