### ISSUE TITLE
[1.12.2] Smithing Table not accepting damaged items in CraftTweaker recipes

### ISSUE THREAD

**Issue by Urbancase** [thedarkcolour/Future-MC#316]
I am playing in a modpack and, while full-durability items work as intended, items with damaged durabilities cannot be used in the Smithing Table. 

![Screenshot (300)](https://user-images.githubusercontent.com/80189509/208596679-bca755fb-e8f8-411a-b7ce-094103b46164.png)

Is this an intentional feature and, if so, are there any ways to make items with varying durability states valid for Smithing Table recipes?

**Comment by zeng-github01** [comment]
[Related code](https://github.com/thedarkcolour/Future-MC/blob/3e9b7716ac339027cdcc3af4fc5a82318a32ce0d/src/main/java/thedarkcolour/futuremc/compat/crafttweaker/SmithingTable.java#L44)

[Related code](https://github.com/thedarkcolour/Future-MC/blob/3e9b7716ac339027cdcc3af4fc5a82318a32ce0d/src/main/java/thedarkcolour/futuremc/recipe/smithing/SmithingRecipes.kt#L16)

After investigation, this may be due to the fact that the interface for adding recipes uses a meta value other than 32767, which is said to represent any damage value items.

**Comment by thedarkcolour** [comment]
Fixed in 0.2.18
