### ISSUE TITLE
Smoker and Blast Furnace Recipes don't work properly

### ISSUE THREAD

**Issue by alex-fantastico** [thedarkcolour/Future-MC#80]
Smoker and Blast Furnace recipes seem to be inherited from Furnace recipes. New Blast Furnace and Smoker recipes (added with CT) show up in JEI, but don't actually function. 

In addition, if the furnace recipes are changed for an item which is already smeltable in the Blast Furnace or Smoker, they will output the item that the furnace is supposed to, although they won't show that in JEI. 

For example, I wanted to make the furnace output 6 Lapis Lazuli when smelting Lapis Ore, and make the Blast Furnace output a Lapis Block. But the Blast Furnace outputted 6 Lapis Lazuli, like the furnace should. I tested it with the Smoker and got the same results (I swapped outputs for some cooked meat in the furnace, and the Smoker had those same swapped outputs). I also tested the Campfire but it works as expected, apart from not being able to remove recipes, and items being burned, which have been noted already. 

I did one final test, removing a shared furnace and blast furnace recipe from the furnace. The recipe was also removed from the blast furnace. But still shows up in JEI. 

I don't know how the code works, but it seems like the Smoker and Blast Furnace are pulling from the Furnace's recipe list instead of their own? But only for their allotted items. I hope that helps to get the bottom of this.

**Comment by thedarkcolour** [comment]
The code pulls from its own recipes. I don’t remember how it works in this release because I’m going to change it to be more consistent with other machines in my mod, but it seems to be an issue with the way I implement CraftTweaker. I now realize what I’ve done wrong as I’m typing this. I stopped using IActions for CraftTweaker recipes, and using them in the upcoming release may solve the problem. So it’s an issue with how I implement CraftTweaker functionality, not with my furnace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joegman** [comment]
Hey @thedarkcolour any update on this fix? I am still experiencing this issue in alpha 0.2.02
